env:
    MANIFEST: https://github.com/PixysOS/manifest -b thirteen
    DEVICE: a73xq
    OEM: samsung
    COMMON: sm7325-common
    DT_LINK: https://github.com/ROM-CUSTOM-SAMSUNG/android_device_samsung_a73xq -b thirteen
    DT_PATH: device/$OEM/$DEVICE
    DT_COMMON_LINK: https://github.com/ROM-CUSTOM-SAMSUNG/android_device_samsung_sm7325-common -b thirteen
    DT_COMMON_PATH: device/$OEM/$COMMON
    VT_LINK: https://github.com/ROM-CUSTOM-SAMSUNG/android_vendor_samsung_a73xq -b thirteen
    VT_PATH: vendor/$OEM/$DEVICE
    VT_COMMON_LINK: https://github.com/ROM-CUSTOM-SAMSUNG/android_vendor_samsung_sm7325-common -b thirteen
    VT_COMMON_PATH: vendor/$OEM/$COMMON
    KT_LINK: https://gitlab.com/nguyenhung9xdev2022/android_kernel_samsung_sm7325 -b thirteen
    PLATFORM: sm7325
    KT_PATH: kernel/$OEM/$PLATFORM
    HARDWARE_LINK: https://github.com/PixelExperience/hardware_samsung -b thirteen
    HARDWARE_PATH: hardware/$OEM
    TARGET: pixys
    EXTRA_CMD: export SKIP_ABI_CHECKS=true
    LUNCH_COMBO: pixys_${DEVICE}-userdebug
    OUTPUT: Pixys*.zip

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 940m  
  container:
      image: ghcr.io/nguyenhung9xdev2022/docker:arch
      cpu: 8
      memory: 32G



  Storage-Checker_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - mkdir -p ~/work
      - cd ~/work
      - repo init --depth=1 -u $MANIFEST
      - repo sync -j4 --force-sync --no-tags --no-clone-bundle
      - git clone $DT_LINK $DT_PATH
      - git clone $DT_COMMON_LINK $DT_COMMON_PATH
      - git clone $VT_LINK $VT_PATH
      - git clone $VT_COMMON_LINK $VT_COMMON_PATH
      - git clone $KT_LINK $KT_PATH
      - rm -rf hardware/samsung
      - git clone $HARDWARE_LINK $HARDWARE_PATH
      - echo "============================"
      - echo "Syncing Complete!"
      - echo "============================"

  Build_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - cd ~/work
      - $EXTRA_CMD
      - export USE_CCACHE=1
      - export CCACHE_EXEC=/usr/bin/ccache
      - ccache -M 50G
      - . build/envsetup.sh
      - lunch "$LUNCH_COMBO"
      - mka -j31 $TARGET
     
  Upload_script:
      - echo "============================"
      - echo "Uploading the Build..."
      - echo "============================"
      - cd ~/work
      - cd out/target/product/"$DEVICE"
      - ls -lh
      - pwd
      - chmod 777 *
      - curl --upload-file $(echo $OUTPUT) https://transfer.sh | tee link.txt && echo " "
      - echo " "
      - echo "============================"
      - echo "Build Uploaded!"
      - echo "Please see the link Below-  "
      - echo "----------------------------"
      - cat link.txt && echo " "
      - echo "============================"
